[project]
name = "dataengineeringcrew"
version = "0.1.0"
description = "dataengineeringcrew using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=0.186.1,<1.0.0"
]

[project.scripts]
dataengineeringcrew = "dataengineeringcrew.main:run"
run_crew = "dataengineeringcrew.main:run"
train = "dataengineeringcrew.main:train"
replay = "dataengineeringcrew.main:replay"
test = "dataengineeringcrew.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
